title: Scott Jespersen 
author: Scott Jespersen
description: Personal website for Scott Jespersen.
baseurl: ""
url: "http://sdjespersen.github.io"
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
